pool:
  vmImage: 'macos-latest'
  demands:
  - java
  - JDK

steps:

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **/*.aar
    TargetFolder: '$(build.artifactstagingdirectory)'